### ISSUE TITLE
data and readme file

### ISSUE THREAD

**Issue by dshizuka** [BIOS967/BIOS967_OBE#1]
Hi David, I looked over your readme file and data. The idea to use your labmate's data is good, and it should work fine for the class, though you only be able to do a couple of simple analyses on this because there's not a ton of additional data here. But it woudl be a useful dataset for learning ways to reformat the data to make it more amenble for analysis, etc.

**Comment by obe90** [comment]
Thank you for the feedback Dr. Shizuka.
