### ISSUE TITLE
Figured out how to read pdb files as text and find the resolution

### ISSUE THREAD

**Issue by dshizuka** [BIOS967/BIOS967_OBE#3]
Hey David, 
I remembered how to use the scan() function to read text-based files and was able to figure out how to find the resolution value. I've provided this in the "batch_import_trial" script file in your GitHub now. Here is my explanation as text:

#you can read the pdb file just as a text file this way:
p1=scan(file="data/pdb_files/1rp0.pdb.gz", what="text")
p2=scan(file="data/pdb_files/7rk0.pdb.gz", what="text")

#this will read the file by each line and tab. So a lot of this will be just one word.
p1

#then, you can just search for "RESOLUTION." with the period at the end. The str_which() function will tell you which item in "p1" gives you the exact match.
library(stringr)
str_which(p1, "RESOLUTION.")

#The item that follows that is the the resolution, so you can look that up by using p1[ ], and adding one to the item number of "RESOLUTION." This should give you "1.60"
p1[str_which(p1, "RESOLUTION.")+1]

#so you just have to save that as a number
as.numeric(p1[str_which(p1, "RESOLUTION.")+1])

#This should then work on other pdb files, like the second one I imported above.
as.numeric(p2[str_which(p2, "RESOLUTION.")+1])

#With this, you should be able to scale up and batch import and process a bunch of pdb files. I'll leave that to you to try!

**Comment by obe90** [comment]
Thank you so much, sir.
